DEBUG: TRUE
SECRET_KEY: # YOUR_SECRET_KEY

GOOGLE:
  CLIENT_ID: #GOOGLE_CLIENT_ID
  CLIENT_SECRET: # GOOGLE_CLIENT_SECRET

FRONTEND:
  REDIRECT_URI: http://localhost:3000/redirect

DATABASE:
    HOST: localhost
    PORT: 5432
    NAME: arxivappdb
    USER: arxivapp
    PASSWORD: Pass123#

ALLOWED_HOSTS:
    - "localhost"
    - "127.0.0.1"